# Generated by Django 4.2.7 on 2024-01-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='updated_by',
        ),
    ]
