# Generated by Django 4.2.7 on 2024-01-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_registration_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='confirm_password',
        ),
    ]
